version: '2'
services:
  - name: apex-launcher
    type: web
    routes:
      - path: /
    env:
      - key: NODE_ENV
        value: production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - port: 8000
        protocol: TCP
    health_check:
      tcp_port: 8000
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    scalability:
      min_instances: 1
      max_instances: 3
      metric: cpu
      target_value: 70
